(()=>{
const style=document.createElement('style');style.textContent=`
.gx-vignette{position:absolute;inset:0;pointer-events:none;z-index:22;background:radial-gradient(circle,transparent 35%,#0008 100%);opacity:0;transition:opacity .25s}.gx-vignette.on{opacity:1}
.gx-lines{position:absolute;inset:-80%;z-index:4;pointer-events:none;background:repeating-conic-gradient(from 0deg,transparent 0 5deg,#fff2 6deg 7deg);animation:gxspin 2.2s linear infinite;opacity:0}.gx-lines.on{opacity:1}
.gx-msg{position:absolute;left:50%;top:19%;transform:translateX(-50%) scale(.4);z-index:28;pointer-events:none;font-size:16px;font-weight:1000;letter-spacing:.12em;white-space:nowrap;text-shadow:0 0 14px currentColor;opacity:0}.gx-msg.on{animation:gxmsg .7s forwards}
.gx-chance{position:absolute;left:50%;top:32%;transform:translateX(-50%) scale(.5);z-index:28;pointer-events:none;font-size:42px;font-weight:1000;font-style:italic;white-space:nowrap;opacity:0;text-shadow:0 0 20px currentColor,0 0 45px currentColor}.gx-chance.on{animation:gxchance .7s forwards}
.gx-star{position:absolute;left:50%;top:51%;width:8px;height:8px;border-radius:50%;background:#fff;z-index:26;pointer-events:none;box-shadow:0 0 15px #fff,0 0 35px #7cf}.gx-star.go{animation:gxstar .75s ease-out forwards}
.gx-rainbow{position:absolute;inset:-30%;z-index:5;pointer-events:none;background:conic-gradient(#ff3158,#ffd52e,#46ff75,#45e7ff,#765dff,#ff42c8,#ff3158);filter:blur(18px);opacity:0;mix-blend-mode:screen}.gx-rainbow.on{animation:gxr .9s forwards}
.gx-white{position:absolute;inset:-20%;z-index:29;pointer-events:none;background:#fff;opacity:0}.gx-white.go{animation:gxwhite .55s forwards}
@keyframes gxspin{to{transform:rotate(360deg)}}@keyframes gxmsg{0%{opacity:0;transform:translateX(-50%) scale(.4)}55%{opacity:1;transform:translateX(-50%) scale(1.15)}100%{opacity:0;transform:translateX(-50%) scale(1)}}@keyframes gxchance{0%{opacity:0;transform:translateX(-50%) scale(.5)}55%{opacity:1;transform:translateX(-50%) scale(1.15)}100%{opacity:0;transform:translateX(-50%) scale(1)}}@keyframes gxstar{to{opacity:0;transform:translate(var(--x),var(--y)) scale(.1)}}@keyframes gxr{0%{opacity:0;transform:scale(.2) rotate(0)}35%{opacity:.9}100%{opacity:0;transform:scale(1.1) rotate(90deg)}}@keyframes gxwhite{0%{opacity:0}18%{opacity:.95}100%{opacity:0}}
.stage.ur .gx-msg,.stage.ur .gx-chance{color:#ffe34f}.stage.ssr .gx-msg,.stage.ssr .gx-chance{color:#ed9aff}.stage.sr .gx-msg,.stage.sr .gx-chance{color:#65eaff}.stage.r .gx-msg,.stage.r .gx-chance{color:#dce8ff}`;document.head.appendChild(style);
function add(){const stage=document.getElementById('stage');if(!stage||stage.querySelector('.gx-vignette'))return;['gx-vignette','gx-lines','gx-rainbow','gx-white'].forEach(c=>{const e=document.createElement('div');e.className=c;stage.appendChild(e)});const m=document.createElement('div');m.className='gx-msg';m.id='gxMsg';stage.appendChild(m);const c=document.createElement('div');c.className='gx-chance';c.id='gxChance';stage.appendChild(c)}
function stars(n=28){const box=document.getElementById('stage');for(let i=0;i<n;i++){const s=document.createElement('i');s.className='gx-star go';const a=Math.random()*Math.PI*2,d=90+Math.random()*360;s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');box.appendChild(s);setTimeout(()=>s.remove(),850)}}
function startFX(){add();const stage=document.getElementById('stage');const v=stage.querySelector('.gx-vignette'),l=stage.querySelector('.gx-lines'),m=document.getElementById('gxMsg');v.classList.add('on');l.classList.add('on');m.textContent='SCOUT START';m.classList.remove('on');void m.offsetWidth;m.classList.add('on');setTimeout(()=>l.classList.remove('on'),1500);setTimeout(()=>v.classList.remove('on'),2200)}
function rarityFX(){add();const stage=document.getElementById('stage'),r=[...stage.classList].find(x=>['r','sr','ssr','ur'].includes(x));const ch=document.getElementById('gxChance'),m=document.getElementById('gxMsg');if(r==='ur'){ch.textContent='!!! ULTRA CHANCE !!!';ch.classList.add('on');stage.querySelector('.gx-rainbow').classList.add('on');stars(55);const w=stage.querySelector('.gx-white');setTimeout(()=>w.classList.add('go'),650)}else if(r==='ssr'){ch.textContent='SUPER CHANCE!';ch.classList.add('on');stars(35)}else if(r==='sr'){ch.textContent='RARE CHANCE!';ch.classList.add('on');stars(24)}else{ch.textContent='RECRUIT';ch.classList.add('on');stars(12)}setTimeout(()=>ch.classList.remove('on'),900);m.textContent=r==='ur'?'ULTRA RARE!!':r==='ssr'?'SUPER RARE!!':r==='sr'?'RARE!!':'RECRUIT!!';m.classList.remove('on');void m.offsetWidth;m.classList.add('on')}
function revealFX(){add();const stage=document.getElementById('stage'),r=[...stage.classList].find(x=>['r','sr','ssr','ur'].includes(x));stars(r==='ur'?80:r==='ssr'?50:30);if(r==='ur'){stage.querySelector('.gx-rainbow').classList.add('on');const w=stage.querySelector('.gx-white');w.classList.remove('go');void w.offsetWidth;w.classList.add('go')}}
const one=document.getElementById('one'),rev=document.getElementById('reveal');if(one)one.addEventListener('click',()=>{setTimeout(startFX,20)});if(rev)rev.addEventListener('click',()=>{revealFX()});
const stage=document.getElementById('stage');if(stage)new MutationObserver(()=>{if(stage.classList.contains('show')){setTimeout(rarityFX,930)}}).observe(stage,{attributes:true,attributeFilter:['class']});
})();