(()=>{
const style=document.createElement('style');style.textContent=`
.gx-vignette{position:absolute;inset:0;pointer-events:none;z-index:22;background:radial-gradient(circle,transparent 28%,#000b 100%);opacity:0}.gx-vignette.on{opacity:1;transition:opacity .2s}
.gx-lines{position:absolute;inset:-80%;z-index:4;pointer-events:none;background:repeating-conic-gradient(from 0deg,transparent 0 4deg,#fff3 5deg 6deg);animation:gxspin 1.4s linear infinite;opacity:0}.gx-lines.on{opacity:1}
.gx-panels{position:absolute;inset:0;z-index:18;pointer-events:none;opacity:0}.gx-panels.on{opacity:1}.gx-panel{position:absolute;left:-10%;width:120%;height:25%;background:linear-gradient(90deg,transparent,#fff2 35%,#fff8 50%,#fff2 65%,transparent);border-top:1px solid #fff7;border-bottom:1px solid #fff7;transform:skewY(-5deg) translateX(-110%)}.gx-panel:nth-child(1){top:22%;animation:panelIn .55s forwards}.gx-panel:nth-child(2){top:48%;animation:panelIn .55s .08s forwards}.gx-panel:nth-child(3){top:74%;animation:panelIn .55s .16s forwards}
.gx-msg{position:absolute;left:50%;top:18%;transform:translateX(-50%) scale(.4);z-index:28;pointer-events:none;font-size:17px;font-weight:1000;letter-spacing:.12em;white-space:nowrap;text-shadow:0 0 14px currentColor;opacity:0}.gx-msg.on{animation:gxmsg .65s forwards}
.gx-chance{position:absolute;left:50%;top:31%;transform:translateX(-50%) scale(.5);z-index:28;pointer-events:none;font-size:40px;font-weight:1000;font-style:italic;white-space:nowrap;opacity:0;text-shadow:0 0 20px currentColor,0 0 55px currentColor}.gx-chance.on{animation:gxchance .7s forwards}
.gx-star{position:absolute;left:50%;top:51%;width:8px;height:8px;border-radius:50%;background:#fff;z-index:26;pointer-events:none;box-shadow:0 0 15px #fff,0 0 35px #7cf}.gx-star.go{animation:gxstar .78s ease-out forwards}
.gx-rainbow{position:absolute;inset:-35%;z-index:5;pointer-events:none;background:conic-gradient(#ff3158,#ffd52e,#46ff75,#45e7ff,#765dff,#ff42c8,#ff3158);filter:blur(20px);opacity:0;mix-blend-mode:screen}.gx-rainbow.on{animation:gxr 1s forwards}
.gx-white{position:absolute;inset:-20%;z-index:29;pointer-events:none;background:#fff;opacity:0}.gx-white.go{animation:gxwhite .55s forwards}
.gx-scan{position:absolute;left:-20%;right:-20%;height:3px;background:#fff;box-shadow:0 0 18px #fff,0 0 45px #65eaff;z-index:27;top:50%;opacity:0}.gx-scan.go{animation:scan .9s forwards}
.gx-count{position:absolute;left:50%;top:58%;transform:translate(-50%,-50%) scale(.7);z-index:28;font-size:14px;letter-spacing:.35em;font-weight:1000;opacity:0}.gx-count.on{animation:count .8s forwards}
@keyframes gxspin{to{transform:rotate(360deg)}}@keyframes panelIn{0%{transform:skewY(-5deg) translateX(-110%)}65%{transform:skewY(-5deg) translateX(4%)}100%{transform:skewY(-5deg) translateX(0)}}
@keyframes gxmsg{0%{opacity:0;transform:translateX(-50%) scale(.4)}55%{opacity:1;transform:translateX(-50%) scale(1.12)}100%{opacity:0;transform:translateX(-50%) scale(1)}}
@keyframes gxchance{0%{opacity:0;transform:translateX(-50%) scale(.5)}55%{opacity:1;transform:translateX(-50%) scale(1.16)}100%{opacity:0;transform:translateX(-50%) scale(1)}}
@keyframes gxstar{to{opacity:0;transform:translate(var(--x),var(--y)) scale(.1)}}
@keyframes gxr{0%{opacity:0;transform:scale(.15) rotate(0)}35%{opacity:.95}100%{opacity:0;transform:scale(1.15) rotate(120deg)}}
@keyframes gxwhite{0%{opacity:0}18%{opacity:.98}100%{opacity:0}}@keyframes scan{0%{opacity:0;top:75%}20%{opacity:1}100%{opacity:0;top:25%}}@keyframes count{0%{opacity:0;transform:translate(-50%,-50%) scale(.7)}30%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) scale(1.25)}}
.stage.ur .gx-msg,.stage.ur .gx-chance{color:#ffe34f}.stage.ssr .gx-msg,.stage.ssr .gx-chance{color:#ed9aff}.stage.sr .gx-msg,.stage.sr .gx-chance{color:#65eaff}.stage.r .gx-msg,.stage.r .gx-chance{color:#dce8ff}
`;document.head.appendChild(style);
function add(){const stage=document.getElementById('stage');if(!stage||stage.querySelector('.gx-vignette'))return;['gx-vignette','gx-lines','gx-rainbow','gx-white','gx-scan'].forEach(c=>{const e=document.createElement('div');e.className=c;stage.appendChild(e)});const panels=document.createElement('div');panels.className='gx-panels';panels.id='gxPanels';for(let i=0;i<3;i++){const e=document.createElement('div');e.className='gx-panel';panels.appendChild(e)}stage.appendChild(panels);const m=document.createElement('div');m.className='gx-msg';m.id='gxMsg';stage.appendChild(m);const c=document.createElement('div');c.className='gx-chance';c.id='gxChance';stage.appendChild(c);const count=document.createElement('div');count.className='gx-count';count.id='gxCount';stage.appendChild(count)}
function stars(n=28){const box=document.getElementById('stage');for(let i=0;i<n;i++){const s=document.createElement('i');s.className='gx-star go';const a=Math.random()*Math.PI*2,d=90+Math.random()*380;s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');box.appendChild(s);setTimeout(()=>s.remove(),900)}}
function msg(text){const m=document.getElementById('gxMsg');m.textContent=text;m.classList.remove('on');void m.offsetWidth;m.classList.add('on')}
function startFX(){add();const stage=document.getElementById('stage'),v=stage.querySelector('.gx-vignette'),l=stage.querySelector('.gx-lines'),p=document.getElementById('gxPanels');v.classList.add('on');l.classList.add('on');p.classList.add('on');msg('SCOUT START');setTimeout(()=>l.classList.remove('on'),1100);setTimeout(()=>p.classList.remove('on'),800);setTimeout(()=>v.classList.remove('on'),1700)}
function rarityFX(){add();const stage=document.getElementById('stage'),r=[...stage.classList].find(x=>['r','sr','ssr','ur'].includes(x));const ch=document.getElementById('gxChance'),m=document.getElementById('gxMsg'),count=document.getElementById('gxCount'),scan=stage.querySelector('.gx-scan');if(r==='ur'){ch.textContent='!!! ULTRA CHANCE !!!';stage.querySelector('.gx-rainbow').classList.add('on');stars(65);const w=stage.querySelector('.gx-white');setTimeout(()=>w.classList.add('go'),520);count.textContent='LIMIT BREAK';count.classList.add('on')}else if(r==='ssr'){ch.textContent='SUPER CHANCE!';stars(40);count.textContent='HIGH GRADE SIGNAL';count.classList.add('on')}else if(r==='sr'){ch.textContent='RARE CHANCE!';stars(28);count.textContent='RARE SIGNAL';count.classList.add('on')}else{ch.textContent='RECRUIT';stars(14);count.textContent='SIGNAL LOCK';count.classList.add('on')}ch.classList.remove('on');void ch.offsetWidth;ch.classList.add('on');msg(r==='ur'?'ULTRA RARE!!':r==='ssr'?'SUPER RARE!!':r==='sr'?'RARE!!':'RECRUIT!!');scan.classList.remove('go');void scan.offsetWidth;scan.classList.add('go');setTimeout(()=>{ch.classList.remove('on');count.classList.remove('on')},900)}
function revealFX(){add();const stage=document.getElementById('stage'),r=[...stage.classList].find(x=>['r','sr','ssr','ur'].includes(x));stars(r==='ur'?95:r==='ssr'?60:36);if(r==='ur'){stage.querySelector('.gx-rainbow').classList.add('on');const w=stage.querySelector('.gx-white');w.classList.remove('go');void w.offsetWidth;w.classList.add('go')}msg('EMPLOYEE ACQUIRED');}
const one=document.getElementById('one'),rev=document.getElementById('reveal');if(one)one.addEventListener('click',()=>setTimeout(startFX,20));if(rev)rev.addEventListener('click',()=>revealFX());
const stage=document.getElementById('stage');if(stage)new MutationObserver(()=>{if(stage.classList.contains('show')){setTimeout(rarityFX,930)}}).observe(stage,{attributes:true,attributeFilter:['class']});
})();